# Generated by Django 2.2.9 on 2020-07-31 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choices1', models.CharField(max_length=100)),
                ('selected_choices2', models.CharField(max_length=100)),
                ('selected_choices3', models.CharField(max_length=100)),
                ('selected_choices4', models.CharField(max_length=100)),
                ('selected_choices5', models.CharField(max_length=100)),
                ('selected_choices6', models.CharField(max_length=100)),
                ('selected_choices7', models.CharField(max_length=100)),
                ('selected_choices8', models.CharField(max_length=100)),
                ('selected_choices9', models.CharField(max_length=100)),
                ('selected_choices10', models.CharField(max_length=100)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
