# Generated by Django 2.2.9 on 2020-07-31 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_create_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_quiz',
            name='user_name',
        ),
    ]
